{% set name = "marching_cubes" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ilastik/marching_cubes/archive/{{ version }}.tar.gz
  sha256: e173ca9a79382ff21f25dad5094133ad524d0958de773d8ea129a431d0a242de
  patches:
    # MSVC only supports openmp 2.0 syntax - there unsigned loop counter will
    # not compile. Can be removed as soon as MSVC supports newer omp version
    - 0001-ssize_t-in-parallel-fors-for-windows.patch  # [win]

build:
  number: 4
  ignore_run_exports_from:
    # need to find CMake data at build time, but no linkage
    - libboost-devel

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - libboost-devel
    - pybind11
  run:
    - python
    - numpy >=1.12


test:
  imports:
    - marching_cubes

about:
  home: https://github.com/ilastik/marching_cubes
  summary: 'A fast marching cubes implementation in C++ with python bindings.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ilastik/marching_cubes

extra:
  recipe-maintainers:
    - k-dominik
